version: "3"

services:

  mopidy:
    build:
      context: mopidy/
    command: mopidy
    ports:
     - 6680:6680
    depends_on:
      - icecast
  
  icecast:
    build:
      context: icecast/
    ports:
    - 8000:8000
